name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/release.yml'
      - '.github/FUNDING.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/release.yml'
      - '.github/FUNDING.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.22.1

      - name: Install deps
        shell: bash
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev xorg-dev

      - name: Build for linux
        run: go build -o flxvwr-darwin-x64 .

      - name: Run tests
        run: go test -v ./...

  test-aur:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Version
        id: get_version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AURSSH }}" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key

      - name: Add SSH Known Hosts
        run: |
          ssh-keyscan -t rsa,ecdsa,ed25519 aur.archlinux.org >> ~/.ssh/known_hosts

      - name: Configure SSH Client
        run: |
          echo "Host aur.archlinux.org" >> ~/.ssh/config
          echo "  User aur" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/private.key" >> ~/.ssh/config
          echo "  StrictHostKeyChecking yes" >> ~/.ssh/config
          echo "  UserKnownHostsFile ~/.ssh/known_hosts" >> ~/.ssh/config

      - name: Clone AUR Repository
        run: git clone ssh://aur@aur.archlinux.org/flxvwr-bin.git

      - name: Cat PKGBUILD (before)
        run: cat flxvwr-bin/PKGBUILD

      - name: Cat .SRCINFO (before)
        run: cat flxvwr-bin/.SRCINFO

      - name: Update PKGBUILD
        run: |
          cd flxvwr-bin
          sed -i "s/pkgver=.*/pkgver=$VERSION/" PKGBUILD

      - name: Update .SRCINFO
        run: |
          cd flxvwr-bin
          makepkg --printsrcinfo > .SRCINFO

      - name: Cat PKGBUILD (after)
        run: cat flxvwr-bin/PKGBUILD
        
      - name: Cat .SRCINFO (after)
        run: cat flxvwr-bin/.SRCINFO
