name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/release.yml'
      - '.github/FUNDING.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/release.yml'
      - '.github/FUNDING.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.22.1

      - name: Install deps
        shell: bash
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev xorg-dev

      - name: Build for linux
        run: go build -o flxvwr-darwin-x64 .

      - name: Run tests
        run: go test -v ./...

  test-aur:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Update system
        run: |
          pacman -Syu --noconfirm

      - name: Install dependencies
        run: |
          pacman -S --noconfirm base-devel git openssh

      - name: Get Release Version
        id: get_version
        run: |
          VERSION="v0.0.3"
          VERSION="${VERSION#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Add SSH Key
        uses: PhutureCorp/container-ssh-agent@v0.0.1
        with:
          ssh-private-key: ${{ secrets.AURSSH }}
          home-dir: "/root"

      - name: Set Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN" >> ~/.ssh/known_hosts
          echo "aur.archlinux.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKF9vAFWdgm9Bi8uc+tYRBmXASBb5cB5iZsB7LOWWFeBrLp3r14w0/9S2vozjgqY5sJLDPONWoTTaVTbhe3vwO8CBKZTEt1AcWxuXNlRnk9FliR1/eNB9uz/7y1R0+c1Md+P98AJJSJWKN12nqIDIhjl2S1vOUvm7FNY43fU2knIhEbHybhwWeg+0wxpKwcAd/JeL5i92Uv03MYftOToUijd1pqyVFdJvQFhqD4v3M157jxS5FTOBrccAEjT+zYmFyD8WvKUa9vUclRddNllmBJdy4NyLB8SvVZULUPrP3QOlmzemeKracTlVOUG1wsDbxknF1BwSCU7CmU6UFP90kpWIyz66bP0bl67QAvlIc52Yix7pKJPbw85+zykvnfl2mdROsaT8p8R9nwCdFsBc9IiD0NhPEHcyHRwB8fokXTajk2QnGhL+zP5KnkmXnyQYOCUYo3EKMXIlVOVbPDgRYYT/XqvBuzq5S9rrU70KoI/S5lDnFfx/+lPLdtcnnEPk=" >> ~/.ssh/known_hosts
          echo "aur.archlinux.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLMiLrP8pVi5BFX2i3vepSUnpedeiewE5XptnUnau+ZoeUOPkpoCgZZuYfpaIQfhhJJI5qgnjJmr4hyJbe/zxow=" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Clone AUR Repository
        run: |
          git clone ssh://aur@aur.archlinux.org/flxvwr-bin.git

      - name: Update PKGBUILD
        run: |
          cd flxvwr-bin
          sed -i "s/pkgver=.*/pkgver=$VERSION/" PKGBUILD

      - name: Update .SRCINFO
        run: |
          cd flxvwr-bin
          makepkg --printsrcinfo > .SRCINFO

      - name: Cat PKGBUILD (after)
        run: cat flxvwr-bin/PKGBUILD
        
      - name: Cat .SRCINFO (after)
        run: cat flxvwr-bin/.SRCINFO
