name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install deps
        shell: bash
        run: |
          pacman -Syu --noconfirm go gcc xorg-server-devel libxcursor libxrandr libxinerama libxi

      - name: Build for linux
        run: go build -o flxvwr-darwin-x64 .
