name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.22.1

      - name: Install deps
        shell: bash
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev xorg-dev

      - name: Build for linux
        run: go build -o flxvwr-darwin-x64 .

      - name: Run tests
        run: go test -v ./...

  build-darwin-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.22.1

      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Download Icon
        run: curl -o icon.png https://i.ibb.co/RNpWkb6/flxvwr.png

      - name: Build for darwin (Apple Silicon)
        run: |
          mkdir -p build/arm64
          GOARCH=arm64 fyne package -os darwin -icon icon.png -name build/arm64/flxvwr

      - name: Ad-Hoc Code Signing for arm64
        run: |
          codesign --sign - --force --deep build/arm64/flxvwr.app

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG for arm64
        run: |
          create-dmg \
            --volname "flxvwr Installer (arm64)" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --app-drop-link 400 150 \
            "build/arm64/flxvwr-arm64.dmg" \
            "build/arm64/flxvwr.app" \

      - name: Upload arm64 DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flxvwr-arm64.dmg
          path: build/arm64/flxvwr-arm64.dmg

  build-darwin-x64:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.22.1

      - name: Install Fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Download Icon
        run: curl -o icon.png https://i.ibb.co/RNpWkb6/flxvwr.png

      - name: Build for darwin (Intel)
        run: |
          mkdir -p build/x64
          GOARCH=amd64 fyne package -os darwin -icon icon.png -name build/x64/flxvwr

      - name: Ad-Hoc Code Signing for x64
        run: |
          codesign --sign - --force --deep build/x64/flxvwr.app

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG for x64
        run: |
          create-dmg \
            --volname "flxvwr Installer (x64)" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --app-drop-link 400 150 \
            "build/x64/flxvwr-x64.dmg" \
            "build/x64/flxvwr.app" \

      - name: Upload x64 DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flxvwr-x64.dmg
          path: build/x64/flxvwr-x64.dmg
