name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/release.yml'
      - '.github/FUNDING.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/release.yml'
      - '.github/FUNDING.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.22.1

      - name: Install deps
        shell: bash
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev xorg-dev

      - name: Build for linux
        run: go build -o flxvwr-darwin-x64 .

      - name: Run tests
        run: go test -v ./...

  test-aur:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    steps:
      - name: Get Release Version
        id: get_version
        run: |
          VERSION="v0.0.3"
          VERSION="${VERSION#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Install SSH and Git
        run: |
          pacman -Sy --noconfirm openssh git

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AURSSH }}" > ~/.ssh/aur
          echo "${{ secrets.AURPUBSSH }}" > ~/.ssh/aur.pub
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.AURSSH }}"
          chmod 600 ~/.ssh/aur
          chmod 600 ~/.ssh/aur.pub
          ssh-keyscan -t rsa,ed25519,ecdsa aur.archlinux.org >> ~/.ssh/known_hosts || true 
          touch ~/.ssh/config
          echo "Host aur.archlinux.org" >> ~/.ssh/config
          echo "  User aur" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/aur" >> ~/.ssh/config

      - name: Cat SSH config
        run: |
          cat ~/.ssh/config
          cat ~/.ssh/known_hosts

      - name: Checkout aur repo
        run: |
          git clone ssh://aur@aur.archlinux.org/flxvwr-bin.git

      - name: Cat PKGBUILD (before)
        run: cat flxvwr-bin/PKGBUILD

      - name: Cat .SRCINFO (before)
        run: cat flxvwr-bin/.SRCINFO

      - name: Update PKGBUILD
        run: |
          cd flxvwr-bin
          sed -i "s/pkgver=.*/pkgver=$VERSION/" PKGBUILD

      - name: Update .SRCINFO
        run: |
          cd flxvwr-bin
          rm -f .SRCINFO
          makepkg --printsrcinfo > .SRCINFO

      - name: Cat PKGBUILD (after)
        run: cat flxvwr-bin/PKGBUILD

      - name: Cat .SRCINFO (after)
        run: cat flxvwr-bin/.SRCINFO

