name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.22.1

      - name: Install deps
        shell: bash
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev xorg-dev

      - name: Build for linux
        run: go build -o flxvwr-darwin-x64 .

      - name: Run tests
        run: go test -v ./...

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.22.1

      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
  
      - name: Download Icon
        run: curl -o icon.png https://i.ibb.co/RNpWkb6/flxvwr.png
  
      - name: Build for Windows
        run: |
          mkdir -p build/windows
          GOARCH=amd64 fyne package -os windows -icon icon.png -name flxvwr
          mv flxvwr.exe build/windows/flxvwr.exe
  
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flxvwr-windows.exe
          path: build/windows/flxvwr.exe
