name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'Licence.md'
      - '.gitignore'
      - '.github/workflows/release.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'Licence.md'
      - '.gitignore'
      - '.github/workflows/release.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.22.1

      - name: Install deps
        shell: bash
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev xorg-dev

      - name: Build for linux
        run: go build -o flxvwr-darwin-x64 .

      - name: Run tests
        run: go test -v ./...

