
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.22.1
      
      - name: Install GCC
        shell: bash
        run: brew install gcc

      - name: Build for linux
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o flxvwr-darwin-x64 .
