name: Publish

on:
  release:
    types: [published]

jobs:
  publish-aur:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Update system
        run: |
          pacman -Syu --noconfirm

      - name: Install dependencies
        run: |
          pacman -S --noconfirm base-devel git openssh

      - name: Get Release Version
        id: get_version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Add SSH Key
        uses: PhutureCorp/container-ssh-agent@v0.0.1
        with:
          ssh-private-key: ${{ secrets.AURSSH }}
          home-dir: "/root"

      - name: Set Known Hosts
        run: |
          mkdir -p /root/.ssh
          echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN" >> /root/.ssh/known_hosts
          echo "aur.archlinux.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKF9vAFWdgm9Bi8uc+tYRBmXASBb5cB5iZsB7LOWWFeBrLp3r14w0/9S2vozjgqY5sJLDPONWoTTaVTbhe3vwO8CBKZTEt1AcWxuXNlRnk9FliR1/eNB9uz/7y1R0+c1Md+P98AJJSJWKN12nqIDIhjl2S1vOUvm7FNY43fU2knIhEbHybhwWeg+0wxpKwcAd/JeL5i92Uv03MYftOToUijd1pqyVFdJvQFhqD4v3M157jxS5FTOBrccAEjT+zYmFyD8WvKUa9vUclRddNllmBJdy4NyLB8SvVZULUPrP3QOlmzemeKracTlVOUG1wsDbxknF1BwSCU7CmU6UFP90kpWIyz66bP0bl67QAvlIc52Yix7pKJPbw85+zykvnfl2mdROsaT8p8R9nwCdFsBc9IiD0NhPEHcyHRwB8fokXTajk2QnGhL+zP5KnkmXnyQYOCUYo3EKMXIlVOVbPDgRYYT/XqvBuzq5S9rrU70KoI/S5lDnFfx/+lPLdtcnnEPk=" >> /root/.ssh/known_hosts
          echo "aur.archlinux.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLMiLrP8pVi5BFX2i3vepSUnpedeiewE5XptnUnau+ZoeUOPkpoCgZZuYfpaIQfhhJJI5qgnjJmr4hyJbe/zxow=" >> /root/.ssh/known_hosts
          chmod 644 /root/.ssh/known_hosts

      - name: Clone AUR Repository
        run: |
          git clone ssh://aur@aur.archlinux.org/flxvwr-bin.git

      - name: Create non-root user
        run: |
          useradd -m builduser
          echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builduser:builduser flxvwr-bin

      - name: Get SHA256sums
        run: |
          curl -sL https://github.com/justjcurtis/flxvwr/releases/download/v$VERSION/flxvwr-x64-v$VERSION.tar.xz | sha256sum | cut -d ' ' -f 1 > flxvwr-bin/flxvwr.sha256sum
          curl -sL https://raw.githubusercontent.com/justjcurtis/flxvwr/main/LICENSE | sha256sum | cut -d ' ' -f 1 > flxvwr-bin/LICENSE.sha256sum

      - name: Update PKGBUILD
        run: |
          cd flxvwr-bin
          sed -i "s/pkgver=.*/pkgver=$VERSION/" PKGBUILD
          sed -i "s/sha256sums=.*/sha256sums=('$(cat flxvwr.sha256sum)' '$(cat LICENSE.sha256sum)')/" PKGBUILD

      - name: Update .SRCINFO
        run: |
          cd flxvwr-bin
          sudo -u builduser makepkg --printsrcinfo > .SRCINFO

      - name: Commit and push
        run: |
          git config --global --add safe.directory flxvwr-bin
          cd flxvwr-bin
          git config --global user.email "justjcurtis@gmail.com"
          git config --global user.name "justjcurtis"
          git add PKGBUILD .SRCINFO
          git commit -m "Update to v$VERSION"
          git push
